### ISSUE TITLE
Scripting Q & A JavaScript sequence

### ISSUE THREAD

**Issue by ebeshero** [Emotion-Web/Senior_Project_Angular#24]
Two arrays, correlated by position of values:
Array 1:  images 
Array 2: emotion-words

Random number generator yields an integer between 0 and length (= the total number of images in your array -1 b/c we start counting from zero)

The position value we retrieve selects two things:
1. the image 
2. its correct emotion-word 

The option list is static, but the correct answer must change as the image changes.

**Comment by Cameron-Bigi** [comment]
https://github.com/Emotion-Web/Senior_Project_Angular/blob/main/JS%20Course/Project%2002-%20Handling%20User%20Input/script2.js

**Comment by ebeshero** [comment]
@Cameron-Bigi Good news! I got a little help to debug the scorekeeping: The issue was where we were positioning the event listener for clicking the list items: it was accumulating every selection and continuing to send them on to the checkAnswer() function. I moved a few things around and it seems to be score-keeping correctly and reporting results! Pull in the latest code from tdoay, take a look and see how it's functioning for you. 

My hope is that you can easily build on this code and continue developing content for your game! 
Also, I'm planning to help out tomorrow at the Steam Fair: I can attend for a bit with you, maybe help answer questions from the attendees about DIGIT, etc. See you there at Junker Center at 5:30? Or let me know if I can help you set up stuff.

**Comment by Cameron-Bigi** [comment]
@ebeshero Hi Professor I’m currently at the steam fair in the junker center setting up my table. Just wondering if you were gonna stop by and if so at what time. I wanted to get here a little bit early to set up and make sure everything works.
